coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "**/__pycache__/"
  - "*.pyc"
  - ".env*"
  - "docker-compose*.yml"
  - "Dockerfile*"
  - "scripts/"
  - "docs/"

github_checks:
  annotations: true

flags:
  unittests:
    paths:
      - bot/
      - shared/